# Generated by Django 4.2.5 on 2023-09-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_newuser_email_alter_newuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('targetDate', models.DateField()),
                ('isCompleted', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='notCompleted',
        ),
        migrations.AddField(
            model_name='newuser',
            name='Task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.task'),
        ),
    ]
