# Generated by Django 4.2.5 on 2023-09-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_task_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
    ]
