# Generated by Django 4.2.5 on 2023-10-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='createdBy',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
